/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CafeManagementSystems;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Random;

public class CafeManagementSystem extends javax.swing.JFrame {
double[] drink=new double[5];
double[] cake=new double[8];
double[] cost=new double[3];
double[] i   =new double[11];
    /**
     * Creates new form CafeManagementSystem
     */
    public CafeManagementSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jcheckcupcake = new javax.swing.JCheckBox();
        jcheckcofeecake = new javax.swing.JCheckBox();
        jcheckstrawberycake = new javax.swing.JCheckBox();
        jcheckchoclatecake = new javax.swing.JCheckBox();
        jcheckblueberrycake = new javax.swing.JCheckBox();
        jtxtcofeecake = new javax.swing.JTextField();
        jtxtstrawberycake = new javax.swing.JTextField();
        jtxtcupcake = new javax.swing.JTextField();
        jtxtblueberrycake = new javax.swing.JTextField();
        jtxtchoclatecake = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jlbltax = new javax.swing.JLabel();
        jlblsubtotal = new javax.swing.JLabel();
        jlbltotal = new javax.swing.JLabel();
        jtxttax = new javax.swing.JLabel();
        jtxttotal = new javax.swing.JLabel();
        jtxtsubtotal = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jchecktea = new javax.swing.JCheckBox();
        jcheckcofee = new javax.swing.JCheckBox();
        jcheckcappuccino = new javax.swing.JCheckBox();
        jcheckcolddrink = new javax.swing.JCheckBox();
        jcheckcoldcofee = new javax.swing.JCheckBox();
        jtxtcofee = new javax.swing.JTextField();
        jtxtcappuccino = new javax.swing.JTextField();
        jtxttea = new javax.swing.JTextField();
        jtxtcoldcofee = new javax.swing.JTextField();
        jtxtcolddrink = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtreciept = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jlblcostofdrinks = new javax.swing.JLabel();
        jlblcostofcakes = new javax.swing.JLabel();
        jlblservicecharges = new javax.swing.JLabel();
        jtxtcakes = new javax.swing.JLabel();
        jtxtservicecharges = new javax.swing.JLabel();
        jtxtdrinks = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        JRESTBUTTON = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jbutnreciept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1368, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel2.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 70)); // NOI18N
        jLabel1.setText("CAFE MANAGEMENT SYSTEM");

        jLabel2.setFont(new java.awt.Font("Webdings", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addGap(115, 115, 115)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1180, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jcheckcupcake.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcheckcupcake.setText("CUP CAKE");
        jcheckcupcake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcheckcupcakeMouseClicked(evt);
            }
        });
        jcheckcupcake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckcupcakeActionPerformed(evt);
            }
        });

        jcheckcofeecake.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcheckcofeecake.setText("COFEE CAKE");
        jcheckcofeecake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcheckcofeecakeMouseClicked(evt);
            }
        });
        jcheckcofeecake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckcofeecakeActionPerformed(evt);
            }
        });

        jcheckstrawberycake.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcheckstrawberycake.setText("STRAWBERY CAKE");
        jcheckstrawberycake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcheckstrawberycakeMouseClicked(evt);
            }
        });

        jcheckchoclatecake.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcheckchoclatecake.setText("CHOCLATE CAKE");
        jcheckchoclatecake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcheckchoclatecakeMouseClicked(evt);
            }
        });

        jcheckblueberrycake.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcheckblueberrycake.setText("BLUE BERRY CAKE");
        jcheckblueberrycake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcheckblueberrycakeMouseClicked(evt);
            }
        });

        jtxtcofeecake.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtcofeecake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcofeecake.setText("0");
        jtxtcofeecake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtcofeecake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtcofeecakeMouseClicked(evt);
            }
        });

        jtxtstrawberycake.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtstrawberycake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtstrawberycake.setText("0");
        jtxtstrawberycake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtstrawberycake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtstrawberycakeMouseClicked(evt);
            }
        });

        jtxtcupcake.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtcupcake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcupcake.setText("0");
        jtxtcupcake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtcupcake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtcupcakeMouseClicked(evt);
            }
        });

        jtxtblueberrycake.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtblueberrycake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtblueberrycake.setText("0");
        jtxtblueberrycake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtblueberrycake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtblueberrycakeMouseClicked(evt);
            }
        });

        jtxtchoclatecake.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtchoclatecake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtchoclatecake.setText("0");
        jtxtchoclatecake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtchoclatecake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtchoclatecakeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcheckstrawberycake)
                    .addComponent(jcheckcofeecake)
                    .addComponent(jcheckcupcake)
                    .addComponent(jcheckchoclatecake)
                    .addComponent(jcheckblueberrycake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtblueberrycake, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtcofeecake, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtstrawberycake, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtcupcake, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtchoclatecake, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jtxtcupcake, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtcofeecake, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcheckcofeecake)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jcheckcupcake)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcheckstrawberycake)
                    .addComponent(jtxtstrawberycake, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcheckchoclatecake)
                    .addComponent(jtxtchoclatecake, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtblueberrycake, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcheckblueberrycake))
                .addGap(19, 19, 19))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jlbltax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbltax.setText("TAX");

        jlblsubtotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblsubtotal.setText("SUB TOTAL");

        jlbltotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbltotal.setText("TOTAL");

        jtxttax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxttax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jtxttax.setText("0.00");
        jtxttax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxttotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxttotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jtxttotal.setText("0.00");
        jtxttotal.setToolTipText("");
        jtxttotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtsubtotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtsubtotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jtxtsubtotal.setText("0.00");
        jtxtsubtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbltax)
                    .addComponent(jlbltotal)
                    .addComponent(jlblsubtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jtxttax, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbltax)
                    .addComponent(jtxttax, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jlblsubtotal)
                        .addGap(20, 20, 20)
                        .addComponent(jlbltotal))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jchecktea.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jchecktea.setText("TEA");
        jchecktea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcheckteaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcheckteaMouseEntered(evt);
            }
        });
        jchecktea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckteaActionPerformed(evt);
            }
        });

        jcheckcofee.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcheckcofee.setText("C0FEE");
        jcheckcofee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcheckcofeeMouseClicked(evt);
            }
        });

        jcheckcappuccino.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcheckcappuccino.setText("CAPPUCCINO");
        jcheckcappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcheckcappuccinoMouseClicked(evt);
            }
        });

        jcheckcolddrink.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcheckcolddrink.setText("COLD DRINK");
        jcheckcolddrink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcheckcolddrinkMouseClicked(evt);
            }
        });

        jcheckcoldcofee.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcheckcoldcofee.setText("COLD COFEE");
        jcheckcoldcofee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcheckcoldcofeeMouseClicked(evt);
            }
        });

        jtxtcofee.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtcofee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcofee.setText("0");
        jtxtcofee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtcofee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtcofeeMouseClicked(evt);
            }
        });

        jtxtcappuccino.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtcappuccino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcappuccino.setText("0");
        jtxtcappuccino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtcappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtcappuccinoMouseClicked(evt);
            }
        });
        jtxtcappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcappuccinoActionPerformed(evt);
            }
        });

        jtxttea.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxttea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxttea.setText("0");
        jtxttea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxttea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtteaMouseClicked(evt);
            }
        });
        jtxttea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtteaActionPerformed(evt);
            }
        });

        jtxtcoldcofee.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtcoldcofee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcoldcofee.setText("0");
        jtxtcoldcofee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtcoldcofee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtcoldcofeeMouseClicked(evt);
            }
        });

        jtxtcolddrink.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtcolddrink.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcolddrink.setText("0");
        jtxtcolddrink.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jtxtcolddrink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtcolddrinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jcheckcappuccino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(jtxtcappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jcheckcolddrink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtcolddrink, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jcheckcoldcofee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtcoldcofee, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jchecktea, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcheckcofee))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcofee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxttea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jchecktea)
                        .addGap(24, 24, 24)
                        .addComponent(jcheckcofee))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jtxttea, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jtxtcofee, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcheckcappuccino)
                    .addComponent(jtxtcappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcheckcolddrink)
                    .addComponent(jtxtcolddrink, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcheckcoldcofee)
                    .addComponent(jtxtcoldcofee, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jtxtreciept.setColumns(20);
        jtxtreciept.setRows(5);
        jScrollPane1.setViewportView(jtxtreciept);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jlblcostofdrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblcostofdrinks.setText("COST OF DRINKS");

        jlblcostofcakes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblcostofcakes.setText("COST OF CAKES");

        jlblservicecharges.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblservicecharges.setText("SERVICE CHARGES");

        jtxtcakes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtcakes.setText("0.00");
        jtxtcakes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtservicecharges.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtservicecharges.setText("15.16");
        jtxtservicecharges.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtdrinks.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtdrinks.setText("0.00");
        jtxtdrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblcostofdrinks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtdrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblservicecharges)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtservicecharges, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlblcostofcakes, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtcakes, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblcostofdrinks)
                    .addComponent(jtxtdrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtcakes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblcostofcakes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblservicecharges)
                    .addComponent(jtxtservicecharges, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jlblcostofcakes.getAccessibleContext().setAccessibleDescription("");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("TOTAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        JRESTBUTTON.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JRESTBUTTON.setText("RESET");
        JRESTBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRESTBUTTONActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jbutnreciept.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbutnreciept.setText("RECIEPT");
        jbutnreciept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutnrecieptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbutnreciept)
                                .addGap(18, 18, 18)
                                .addComponent(JRESTBUTTON)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addGap(41, 41, 41))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton4)
                            .addComponent(JRESTBUTTON)
                            .addComponent(jbutnreciept)
                            .addComponent(jButton1))
                        .addGap(60, 60, 60))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-17, -20, 2550, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void JRESTBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRESTBUTTONActionPerformed
jtxtcupcake.setText("0");
jtxtcofeecake.setText("0");
jtxtstrawberycake.setText("0");
jtxtchoclatecake.setText("0");
jtxtblueberrycake.setText("0");
jtxttea.setText("0");
jtxtcolddrink.setText("0");
jtxtcappuccino.setText("0");
jtxtcofee.setText("0");
jtxtcoldcofee.setText("0");
jchecktea.setSelected(false);
jcheckcofee.setSelected(false);
jcheckcolddrink.setSelected(false);
jcheckcoldcofee.setSelected(false);
jcheckcappuccino.setSelected(false);
jcheckcupcake.setSelected(false);
jcheckstrawberycake.setSelected(false);
jcheckchoclatecake.setSelected(false);
jcheckblueberrycake.setSelected(false);
jcheckcofeecake.setSelected(false);
jtxtreciept.setText(null);
jtxttax.setText("0");
jtxtsubtotal.setText("0");
jtxttotal.setText("0");
jtxtdrinks.setText("0");
jtxtcakes.setText("0");
jtxtservicecharges.setText("0");

    }//GEN-LAST:event_JRESTBUTTONActionPerformed

    private void jtxtcappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcappuccinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcappuccinoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jcheckcupcakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckcupcakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcheckcupcakeActionPerformed

    private void jcheckcofeecakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckcofeecakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcheckcofeecakeActionPerformed

    private void jbutnrecieptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutnrecieptActionPerformed
drink[0]=Double.parseDouble(jtxttea.getText());
drink[1]=Double.parseDouble(jtxtcofee.getText());
drink[2]=Double.parseDouble(jtxtcappuccino.getText());
drink[3]=Double.parseDouble(jtxtcolddrink.getText());
drink[4]=Double.parseDouble(jtxtcoldcofee.getText());

cake[0]=Double.parseDouble(jtxtcupcake.getText());
cake[1]=Double.parseDouble(jtxtcofeecake.getText());
cake[2]=Double.parseDouble(jtxtstrawberycake.getText());
cake[3]=Double.parseDouble(jtxtchoclatecake.getText());
cake[4]=Double.parseDouble(jtxtblueberrycake.getText());
cost[0]=Double.parseDouble(jtxttax.getText());
cost[1]=Double.parseDouble(jtxtsubtotal.getText());
cost[2]=Double.parseDouble(jtxttotal.getText());
//===============================================//

int refs=1325+(int)(Math.random()*4238);

//===============================================//
Calendar timer =Calendar.getInstance();
timer.getTime();
SimpleDateFormat tTime=new SimpleDateFormat("HH:mm:ss");
tTime.format(timer.getTime());
SimpleDateFormat Tdate=new SimpleDateFormat("dd-MMM-yyyy");
Tdate.format(timer.getTime());

jtxtreciept.append("\t\n  CAFE MANAGEMENT SYSTEM:\n\n"+
        "REFRENCE NO:\t\t\t"+refs +
  "\n========================================\t\n"+
 "TEA:\t\t"+drink[0]+
"\nCOFFE:\t\t"+drink[1]+
"\nCAPPUCCINO:\t\t"+drink[2]+
"\nCOLD DRINK:\t\t"+drink[3]+
"\nCOLD COFEE:\t\t"+drink[4]+   
"\n===============================\t\t\n"+
   "CUP CAKES:\t\t"+cake[0]+
   "\nCOFEE CAKES:\t\t"+cake[1]+
   "\nSTRAWBERY CAKES:\t"+cake[2]+
   "\nCHOCLATE CAKES:\t"+cake[3]+
   "\nBLUEBERRY CAKES:\t"+cake[4]+
 "\n========================================\t"+
      "\nTAX:\t"+cost[0]+
      "\nSUB TOTAL:\t"+cost[1]+
      "\nTOTAL:\t"+cost[2]+
 "\n========================================\t"+
        
        "\nDATE:"+Tdate.format(timer.getTime())+
        "\tTIME:"+tTime.format(timer.getTime())+
        "\n\n THANK YOU :) \n"
);


    
    }//GEN-LAST:event_jbutnrecieptActionPerformed

    private void jtxtteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtteaActionPerformed
       
    }//GEN-LAST:event_jtxtteaActionPerformed

    private void jcheckteaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckteaMouseClicked
       double ctea=Double.parseDouble(jtxtdrinks.getText());
       double tea=Double.parseDouble(jtxttea.getText());
       double itea=79.99;
       if(jchecktea.isSelected())
       {
           i[0]=(tea*itea)+ctea;
           String pDrink = String.format("%.2f",i[0]);
           jtxtdrinks.setText(pDrink);
           
       }
    }//GEN-LAST:event_jcheckteaMouseClicked

    private void jcheckteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckteaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcheckteaActionPerformed

    private void jcheckcofeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckcofeeMouseClicked
    double ccofee=Double.parseDouble(jtxtdrinks.getText());
    double cofee=Double.parseDouble(jtxtcofee.getText());
    double icofee=89.00;
    if(jcheckcofee.isSelected())
    {
        i[1]=(cofee*icofee)+ccofee;
        String pDrink=String.format("%.2f",i[1]);
        jtxtdrinks.setText(pDrink);
    }
    }//GEN-LAST:event_jcheckcofeeMouseClicked

    private void jcheckcappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckcappuccinoMouseClicked
double ccappaccino=Double.parseDouble(jtxtdrinks.getText());
double cappaccino=Double.parseDouble(jtxtcappuccino.getText());
double icappaccino=87.50;
if(jcheckcappuccino.isSelected());
{
    i[2]=(cappaccino*icappaccino)+ccappaccino;
    String pDrink=String.format("%.2f",i[2]);
    jtxtdrinks.setText(pDrink);
    
}
    }//GEN-LAST:event_jcheckcappuccinoMouseClicked

    private void jcheckcolddrinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckcolddrinkMouseClicked
double ccolddrink=Double.parseDouble(jtxtdrinks.getText());
double colddrink=Double.parseDouble(jtxtcolddrink.getText());
double icolddrink=29.99;
if(jcheckcolddrink.isSelected());
{
    i[3]=(colddrink*icolddrink)+ccolddrink;
    String pDrink=String.format("%.2f",i[3]);
    jtxtdrinks.setText(pDrink);
    
}
    }//GEN-LAST:event_jcheckcolddrinkMouseClicked

    private void jcheckcoldcofeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckcoldcofeeMouseClicked
double ccoldcofee=Double.parseDouble(jtxtdrinks.getText());
double coldcofee=Double.parseDouble(jtxtcoldcofee.getText());
double icoldcofee=49.99;
if(jcheckcoldcofee.isSelected());
{
    i[4]=(coldcofee*icoldcofee)+ccoldcofee;
    String pDrink=String.format("%.2f",i[4]);
    jtxtdrinks.setText(pDrink);
   
}
    }//GEN-LAST:event_jcheckcoldcofeeMouseClicked

    private void jcheckcupcakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckcupcakeMouseClicked
      double ccupcake=Double.parseDouble(jtxtcakes.getText());
      double cupcake=Double.parseDouble(jtxtcupcake.getText());
      double icupcake=9.99;
      if(jcheckcupcake.isSelected())
      {
          i[5]=(cupcake*icupcake)+ccupcake;
          String pCake=String.format("%.2f",i[5]);
          jtxtcakes.setText(pCake);
      }
    }//GEN-LAST:event_jcheckcupcakeMouseClicked

    private void jcheckcofeecakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckcofeecakeMouseClicked
double ccofeecake=Double.parseDouble(jtxtcakes.getText());
double cofeecake=Double.parseDouble(jtxtcofeecake.getText());
double icofeecake=12.5;
if(jcheckcofeecake.isSelected())
{
    i[6]=(cofeecake*icofeecake)+ccofeecake;
    String pCake=String.format("%.2f",i[6]);
    jtxtcakes.setText(pCake);
}
    }//GEN-LAST:event_jcheckcofeecakeMouseClicked

    private void jcheckstrawberycakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckstrawberycakeMouseClicked
    double cstrawberycake=Double.parseDouble(jtxtcakes.getText());
double strawberycake=Double.parseDouble(jtxtstrawberycake.getText());
double istrawberycake=18.5;
if(jcheckstrawberycake.isSelected())
{
    i[7]=(strawberycake*istrawberycake)+cstrawberycake;
    String pCake=String.format("%.2f",i[7]);
    jtxtcakes.setText(pCake);
}

    }//GEN-LAST:event_jcheckstrawberycakeMouseClicked

    private void jcheckchoclatecakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckchoclatecakeMouseClicked
double cchoclatecake=Double.parseDouble(jtxtcakes.getText());
double choclatecake=Double.parseDouble(jtxtchoclatecake.getText());
double ichoclatecake=16.5;
if(jcheckchoclatecake.isSelected())
{
    i[8]=(choclatecake*ichoclatecake)+cchoclatecake;
    String pCake=String.format("%.2f",i[8]);
    jtxtcakes.setText(pCake);
}

    }//GEN-LAST:event_jcheckchoclatecakeMouseClicked

    private void jcheckblueberrycakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckblueberrycakeMouseClicked
      double cblueberrycake=Double.parseDouble(jtxtcakes.getText());
double blueberrycake=Double.parseDouble(jtxtblueberrycake.getText());
double iblueberrycake=14.5;
if(jcheckblueberrycake.isSelected())
{
    i[9]=(blueberrycake*iblueberrycake)+cblueberrycake;
    String pCake=String.format("%.2f",i[9]);
    jtxtcakes.setText(pCake);
}

    }//GEN-LAST:event_jcheckblueberrycakeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     drink[0]=Double.parseDouble(jtxtcakes.getText());
     drink[1]=Double.parseDouble(jtxtdrinks.getText());
     drink[2]=Double.parseDouble(jtxtservicecharges.getText());
     
     double cTotal=(drink[0]+drink[1]+drink[2]);
     
     String iTax=String.format("%.2f",cTotal/100);
     jtxttax.setText(iTax);
     
     double Subtotal=cTotal;
     String iSubtotal=String.format("%.2f",Subtotal);
     jtxtsubtotal.setText(iSubtotal);
     
     double iTotal=Subtotal;
     String Total=String.format("%.2f",(iTotal+(iTotal/100)));
     jtxttotal.setText(Total);
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcheckteaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckteaMouseEntered
   
    }//GEN-LAST:event_jcheckteaMouseEntered

    private void jtxtteaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtteaMouseClicked
       jtxttea.setText(null);
    }//GEN-LAST:event_jtxtteaMouseClicked

    private void jtxtcofeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtcofeeMouseClicked
        jtxtcofee.setText(null);
    }//GEN-LAST:event_jtxtcofeeMouseClicked

    private void jtxtcappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtcappuccinoMouseClicked
        jtxtcappuccino.setText(null);
    }//GEN-LAST:event_jtxtcappuccinoMouseClicked

    private void jtxtcolddrinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtcolddrinkMouseClicked
     jtxtcolddrink.setText(null);
    }//GEN-LAST:event_jtxtcolddrinkMouseClicked

    private void jtxtcoldcofeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtcoldcofeeMouseClicked
     jtxtcoldcofee.setText(null);
    }//GEN-LAST:event_jtxtcoldcofeeMouseClicked

    private void jtxtcupcakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtcupcakeMouseClicked
      jtxtcupcake.setText(null);
    }//GEN-LAST:event_jtxtcupcakeMouseClicked

    private void jtxtcofeecakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtcofeecakeMouseClicked
       jtxtcofeecake.setText(null);
    }//GEN-LAST:event_jtxtcofeecakeMouseClicked

    private void jtxtstrawberycakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtstrawberycakeMouseClicked
jtxtstrawberycake.setText(null);
    }//GEN-LAST:event_jtxtstrawberycakeMouseClicked

    private void jtxtchoclatecakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtchoclatecakeMouseClicked
jtxtchoclatecake.setText(null);
    }//GEN-LAST:event_jtxtchoclatecakeMouseClicked

    private void jtxtblueberrycakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtblueberrycakeMouseClicked
      jtxtblueberrycake.setText(null);
    }//GEN-LAST:event_jtxtblueberrycakeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CafeManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CafeManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CafeManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CafeManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CafeManagementSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JRESTBUTTON;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbutnreciept;
    private javax.swing.JCheckBox jcheckblueberrycake;
    private javax.swing.JCheckBox jcheckcappuccino;
    private javax.swing.JCheckBox jcheckchoclatecake;
    private javax.swing.JCheckBox jcheckcofee;
    private javax.swing.JCheckBox jcheckcofeecake;
    private javax.swing.JCheckBox jcheckcoldcofee;
    private javax.swing.JCheckBox jcheckcolddrink;
    private javax.swing.JCheckBox jcheckcupcake;
    private javax.swing.JCheckBox jcheckstrawberycake;
    private javax.swing.JCheckBox jchecktea;
    private javax.swing.JLabel jlblcostofcakes;
    private javax.swing.JLabel jlblcostofdrinks;
    private javax.swing.JLabel jlblservicecharges;
    private javax.swing.JLabel jlblsubtotal;
    private javax.swing.JLabel jlbltax;
    private javax.swing.JLabel jlbltotal;
    private javax.swing.JTextField jtxtblueberrycake;
    private javax.swing.JLabel jtxtcakes;
    private javax.swing.JTextField jtxtcappuccino;
    private javax.swing.JTextField jtxtchoclatecake;
    private javax.swing.JTextField jtxtcofee;
    private javax.swing.JTextField jtxtcofeecake;
    private javax.swing.JTextField jtxtcoldcofee;
    private javax.swing.JTextField jtxtcolddrink;
    private javax.swing.JTextField jtxtcupcake;
    private javax.swing.JLabel jtxtdrinks;
    private javax.swing.JTextArea jtxtreciept;
    private javax.swing.JLabel jtxtservicecharges;
    private javax.swing.JTextField jtxtstrawberycake;
    private javax.swing.JLabel jtxtsubtotal;
    private javax.swing.JLabel jtxttax;
    private javax.swing.JTextField jtxttea;
    private javax.swing.JLabel jtxttotal;
    // End of variables declaration//GEN-END:variables
}
